# Generated by Django 4.0.3 on 2022-04-13 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 11, 41, 15, 985096, tzinfo=utc)),
        ),
    ]
