# Generated by Django 4.0.3 on 2022-04-13 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_appointment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 8, 29, 735019, tzinfo=utc), null=True),
        ),
    ]
