# Generated by Django 4.0.3 on 2022-06-22 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_appointment_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 9, 12, 44, 427875, tzinfo=utc), null=True),
        ),
    ]
